# Generated by Django 5.2.1 on 2025-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Admin Dashboard',
                'verbose_name_plural': '📊 Admin Dashboard',
            },
        ),
    ]
